# ISO 3166-1 alpha-2 country codes to English names
COUNTRY_NAMES: dict[str, str] = {
    'AD': 'Andorra', 'AE': 'UAE', 'AF': 'Afghanistan', 'AG': 'Antigua',
    'AL': 'Albania', 'AM': 'Armenia', 'AO': 'Angola', 'AR': 'Argentina',
    'AT': 'Austria', 'AU': 'Australia', 'AZ': 'Azerbaijan', 'BA': 'Bosnia',
    'BB': 'Barbados', 'BD': 'Bangladesh', 'BE': 'Belgium', 'BF': 'Burkina_Faso',
    'BG': 'Bulgaria', 'BH': 'Bahrain', 'BI': 'Burundi', 'BJ': 'Benin',
    'BN': 'Brunei', 'BO': 'Bolivia', 'BR': 'Brazil', 'BS': 'Bahamas',
    'BT': 'Bhutan', 'BW': 'Botswana', 'BY': 'Belarus', 'BZ': 'Belize',
    'CA': 'Canada', 'CD': 'Congo', 'CF': 'Central_Africa', 'CG': 'Congo',
    'CH': 'Switzerland', 'CI': 'Ivory_Coast', 'CL': 'Chile', 'CM': 'Cameroon',
    'CN': 'China', 'CO': 'Colombia', 'CR': 'Costa_Rica', 'CU': 'Cuba',
    'CV': 'Cape_Verde', 'CY': 'Cyprus', 'CZ': 'Czech_Republic',
    'DE': 'Germany', 'DJ': 'Djibouti', 'DK': 'Denmark', 'DM': 'Dominica',
    'DO': 'Dominican_Republic', 'DZ': 'Algeria', 'EC': 'Ecuador', 'EE': 'Estonia',
    'EG': 'Egypt', 'ER': 'Eritrea', 'ES': 'Spain', 'ET': 'Ethiopia',
    'FI': 'Finland', 'FJ': 'Fiji', 'FR': 'France', 'GA': 'Gabon',
    'GB': 'UK', 'GD': 'Grenada', 'GE': 'Georgia', 'GH': 'Ghana',
    'GM': 'Gambia', 'GN': 'Guinea', 'GQ': 'Equatorial_Guinea', 'GR': 'Greece',
    'GT': 'Guatemala', 'GW': 'Guinea_Bissau', 'GY': 'Guyana', 'HN': 'Honduras',
    'HR': 'Croatia', 'HT': 'Haiti', 'HU': 'Hungary', 'ID': 'Indonesia',
    'IE': 'Ireland', 'IL': 'Israel', 'IN': 'India', 'IQ': 'Iraq',
    'IR': 'Iran', 'IS': 'Iceland', 'IT': 'Italy', 'JM': 'Jamaica',
    'JO': 'Jordan', 'JP': 'Japan', 'KE': 'Kenya', 'KG': 'Kyrgyzstan',
    'KH': 'Cambodia', 'KI': 'Kiribati', 'KM': 'Comoros', 'KN': 'Saint_Kitts',
    'KP': 'North_Korea', 'KR': 'South_Korea', 'KW': 'Kuwait', 'KZ': 'Kazakhstan',
    'LA': 'Laos', 'LB': 'Lebanon', 'LC': 'Saint_Lucia', 'LI': 'Liechtenstein',
    'LK': 'Sri_Lanka', 'LR': 'Liberia', 'LS': 'Lesotho', 'LT': 'Lithuania',
    'LU': 'Luxembourg', 'LV': 'Latvia', 'LY': 'Libya', 'MA': 'Morocco',
    'MC': 'Monaco', 'MD': 'Moldova', 'ME': 'Montenegro', 'MG': 'Madagascar',
    'MH': 'Marshall_Islands', 'MK': 'North_Macedonia', 'ML': 'Mali',
    'MM': 'Myanmar', 'MN': 'Mongolia', 'MR': 'Mauritania', 'MT': 'Malta',
    'MU': 'Mauritius', 'MV': 'Maldives', 'MW': 'Malawi', 'MX': 'Mexico',
    'MY': 'Malaysia', 'MZ': 'Mozambique', 'NA': 'Namibia', 'NE': 'Niger',
    'NG': 'Nigeria', 'NI': 'Nicaragua', 'NL': 'Netherlands', 'NO': 'Norway',
    'NP': 'Nepal', 'NR': 'Nauru', 'NZ': 'New_Zealand', 'OM': 'Oman',
    'PA': 'Panama', 'PE': 'Peru', 'PG': 'Papua_New_Guinea', 'PH': 'Philippines',
    'PK': 'Pakistan', 'PL': 'Poland', 'PT': 'Portugal', 'PW': 'Palau',
    'PY': 'Paraguay', 'QA': 'Qatar', 'RO': 'Romania', 'RS': 'Serbia',
    'RU': 'Russia', 'RW': 'Rwanda', 'SA': 'Saudi_Arabia', 'SB': 'Solomon_Islands',
    'SC': 'Seychelles', 'SD': 'Sudan', 'SE': 'Sweden', 'SG': 'Singapore',
    'SI': 'Slovenia', 'SK': 'Slovakia', 'SL': 'Sierra_Leone', 'SM': 'San_Marino',
    'SN': 'Senegal', 'SO': 'Somalia', 'SR': 'Suriname', 'SS': 'South_Sudan',
    'ST': 'Sao_Tome', 'SV': 'El_Salvador', 'SY': 'Syria', 'SZ': 'Eswatini',
    'TD': 'Chad', 'TG': 'Togo', 'TH': 'Thailand', 'TJ': 'Tajikistan',
    'TL': 'Timor_Leste', 'TM': 'Turkmenistan', 'TN': 'Tunisia', 'TO': 'Tonga',
    'TR': 'Turkey', 'TT': 'Trinidad', 'TV': 'Tuvalu', 'TZ': 'Tanzania',
    'UA': 'Ukraine', 'UG': 'Uganda', 'US': 'USA', 'UY': 'Uruguay',
    'UZ': 'Uzbekistan', 'VA': 'Vatican', 'VC': 'Saint_Vincent', 'VE': 'Venezuela',
    'VN': 'Vietnam', 'VU': 'Vanuatu', 'WS': 'Samoa', 'YE': 'Yemen',
    'ZA': 'South_Africa', 'ZM': 'Zambia', 'ZW': 'Zimbabwe',
}
